[versions]
kotlin = "2.1.20"
compose = "1.8.0"
sqldelight = "2.0.2"
pdfbox = "3.0.4"
djl = "0.30.0"
slf4j = "2.0.16"

[libraries]
djl-tokenizers = { module = "ai.djl.huggingface:tokenizers", version.ref = "djl" }
onnxruntime = { module = "com.microsoft.onnxruntime:onnxruntime", version = "1.18.0" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
